/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CalculatorJNI */

#ifndef _Included_CalculatorJNI
#define _Included_CalculatorJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CalculatorJNI
 * Method:    add
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_CalculatorJNI_add
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     CalculatorJNI
 * Method:    sub
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_CalculatorJNI_sub
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     CalculatorJNI
 * Method:    mult
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_CalculatorJNI_mult
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     CalculatorJNI
 * Method:    div
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_CalculatorJNI_div
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
